use_pretrained : False
save_dir: "/gdrive/My Drive/Video_Classification/ActiveLearning/ID3_SGDR_lr_0_01_v1"
logging_file: "/gdrive/My Drive/Video_Classification/ActiveLearning/ID3_SGDR_lr_0_01_v1/logging.txt"
data_dir: "/content/Dataset_v1/Train"
train_list:  "/gdrive/My Drive/Datasets/Frames_Dataset_AL/Dataset_v1/Train.txt"
model_folder: "/gdrive/My Drive/Video_Classification/ActiveLearning/ID3_SGDR_lr_0_01_v0"
model: 'i3d_resnet50_v1_custom'
eval: False
data_aug: "v1"
train_only: False
num_epochs: 20
T_0: 1
T_mult: 2
resume_epoch: 0
lr: 0.0005